cd Chapter03
./gradlew assembleDebug
cd ../Chapter05
./gradlew assembleDebug
cd ../Chapter06
./gradlew assembleDebug
cd ../Chapter07
./gradlew assembleDebug
cd ../Chapter08
./gradlew assembleDebug
cd ../Chapter09
./gradlew assembleDebug
cd ../Chapter10
./gradlew assembleDebug
cd ../Chapter11
./gradlew assembleDebug
cd ../Chapter12
./gradlew assembleDebug
cd ../Chapter13
./gradlew assembleDebug
cd ..